# Add configuration values here, as shown below.

AWS_ACCESS_KEY_ID: "AKIAINLCSYEFMS7FIKKA"
AWS_SECRET_ACCESS_KEY: "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"

OMNIAUTH_PROVIDER_KEY: "l4nirJJvTkDDRaaqXO67tw"
OMNIAUTH_PROVIDER_SECRET: "SLuPfhrIIM8wSZsIqD8cdmqHqcqddidMTGwA00SAKY"

SECRET_KEY_BASE: "f1030f154de102ca1172b1be68f1c1bfe69f03654161ebc9f9c54994a8c1b79e0c1f49f35df4f96a8938c1f0c520fa6a95716e11b112a7f69047dae7231e25bf"

